// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEXpRPPM3mOb0HS8iE3BbIYCH0fkNI8m0',
    appId: '1:593257918219:web:7a52517fcefacc06923c0e',
    messagingSenderId: '593257918219',
    projectId: 'facebook-clone-43e9f',
    authDomain: 'facebook-clone-43e9f.firebaseapp.com',
    storageBucket: 'facebook-clone-43e9f.appspot.com',
    measurementId: 'G-BSJ6E7M742',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_beJx1odd1YmeG2lZkCf5H8FnbvHBOgs',
    appId: '1:593257918219:android:9ff4acf4b0348ef0923c0e',
    messagingSenderId: '593257918219',
    projectId: 'facebook-clone-43e9f',
    storageBucket: 'facebook-clone-43e9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyo7TP41FO7lSxc1WbzDibqQyGXoF8C7U',
    appId: '1:593257918219:ios:7bfde77fa9a161b2923c0e',
    messagingSenderId: '593257918219',
    projectId: 'facebook-clone-43e9f',
    storageBucket: 'facebook-clone-43e9f.appspot.com',
    iosBundleId: 'com.example.practiceFlutter',
  );
}
